### ISSUE TITLE
Jetty library issues

### ISSUE THREAD

**Issue by wolpert** [wolpert/svarm#6]
There are two variants of jetty in the runtime. This seems to be unique to dStore and does not exist in terrapin.
(Though maybe that's changed lately?) The result is after clients call we get the following message:

```
09:08:57.743 [dw-29] [] WARN  o.eclipse.jetty.server.HttpChannel - /v1/tenant/123
java.lang.NoClassDefFoundError: org/eclipse/jetty/http/HttpFields$Mutable
        at ch.qos.logback.access.jetty.RequestLogImpl.makeJettyServerAdapter(RequestLogImpl.java:264)
        at ch.qos.logback.access.jetty.RequestLogImpl.log(RequestLogImpl.java:255)
        at org.eclipse.jetty.server.HttpChannel.onCompleted(HttpChannel.java:911)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:467)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.http.HttpFields$Mutable
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 11 common frames omitted
```

Need to figure out how to stop this.

The culprit originally appears to be the dropwizard metrics library, but evidence for that has failed.  What I've tried to date:

1. Force all dependencies to be of the jetty version pulled in by dropwizard. (Gradle does not make this easy.)
2. Removed metrics completely, including dependencies.
3. Tried to get everything updated to the very latest jetty. (That did not go well)

**Comment by wolpert** [comment]
Well poop... the issue is discussed here: https://github.com/dropwizard/dropwizard/discussions/5821#discussioncomment-5037636

As it turns out, Dropwizard 3.0.x has a fix/workaround in the branch. Neither 3.x nor 4.x are released yet. I'm gonna poke at their branch and see what I can do to also provide a workaround.

The issue as it turns out is in the request logging... I kept thinking I was pulling in the wrong jetty version. Rather logback-access is at fault. In the dropwizard code, the work around is in `dropwizard-request-logging`

**Comment by wolpert** [comment]
Going to wait on this... not actively working on it. It's more noise right now. Dropwizard will end up releasing a new version before we are done with svarm.

**Comment by wolpert** [comment]
Updated to dropwizard 4... done.
